### ISSUE TITLE
[Feature] Add `FixedBytes` and aliases macros

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/core#109]
### Describe the feature you would like

Exported `macro_rules!` that wrap [`hex_literal::hex!`](https://docs.rs/hex-literal) with `$crate::<type>` constructors. Also re-export `hex!` itself

**Comment by startup-dreamer** [comment]
I would like to work on this @DaniPopes could you please provide additional direction on this.

**Comment by prestwich** [comment]
we'd like a wrapper around `hex!` that also instantiates a `alloy_primitives::FixedBytes` so that users can declare a fixed bytes inline easily

- the macro should live in `alloy_primitives` and be exported
- the macro should have thorough documentation
- the internals of the macro are something like `$crate::FixedBytes( hex! { ... } )`

sample code:
```
let my_bytes: FixedBytes<4> = bytes! { "1234 abcd" };
let output = bytes!{ "12 34" } & bytes!{ "ab cd" };

const DOMAIN_HASH: FixedBytes<32> = bytes! { 
    "a191312024065f51f1eb9e5ffc5795890db9e0a5bc0eacb250d5034d1e990302" 
};
```

**Comment by DaniPopes** [comment]
Sorry @startup-dreamer I already had an implementation this morning, you can check out other issues tagged with [good first issue](https://github.com/alloy-rs/core/labels/good%20first%20issue) if you want to take on another issue.

**Comment by startup-dreamer** [comment]
No worries, I will work on some other issue.
